### ISSUE TITLE
Safari. Не работает скрол в некоторых элементах

### ISSUE THREAD

**Issue by JulyJ** [hyoo-ru/mam_mol#130]
**Приложение:** [$mol_app_inventory_demo](https://eigenmethod.github.io/mol/#supply=24CB0157#demo=mol_app_inventory_demo) или [$mol_app_signup_demo](https://eigenmethod.github.io/mol/#supply=24CB0157#demo=mol_app_signup_demo)
**Браузер:** Safari 602.1 (iOS 10.2)
**Разрешение:** 1920 × 1080
**Детали:**

Не работает скролл в некоторых формах, например в блоке с описанием supply. Только то, что выводится на экран доступно. Общий скролл по странице работает, а по блоку с описанием - нет:
![img_0694](https://cloud.githubusercontent.com/assets/4419881/22323695/9aae7010-e3b5-11e6-9ae8-09903bc81efa.PNG)
![img_0698](https://cloud.githubusercontent.com/assets/4419881/22324173/b9b0aeda-e3b8-11e6-9be2-7b78794cf425.PNG)

**Comment by NatalyaBudnikova** [comment]
Не работает скролл в mol_number_demo и mol_code_demo в Safari (ios 10.2.1), разрешение экрана 640×1136
![img_0395](https://cloud.githubusercontent.com/assets/25827903/25525442/a2a53394-2c17-11e7-915a-d45a55c04c6a.PNG)
![img_0396](https://cloud.githubusercontent.com/assets/25827903/25525441/a2a15b8e-2c17-11e7-8615-adf6457c8794.PNG)

**Comment by nin-jin** [comment]
Нужно добавить $mol_scroll.

**Comment by NatalyaBudnikova** [comment]
Еще есть проблема со скроллом в $mol_app_questions: если планшет в вертикальном состоянии изначально - скролла нет, если перевернуть в горизонтальное - скролл появляется.

**Comment by nin-jin** [comment]
Мистика какая-то. Нет идей.

**Comment by nin-jin** [comment]
Это из-за того, что мы вешали приложение сразу на боди. Перенос приложения внутрь боди решает проблему. Большинство приложений уже исправлены. Остальные будут правиться по мере обнаружения.
