### ISSUE TITLE
Keybinding ghost component

### ISSUE THREAD

**Issue by ar2r13** [hyoo-ru/mam_mol#137]
The component which catch an events (keybinding) and some action

**Comment by nin-jin** [comment]
Тут речь о плагине, позволяющем в простой форме биндить вызов экшенов на комбинации хоткеев.

**Comment by nin-jin** [comment]
Сейчас для этого есть модуль [$mol_hotkey](https://github.com/hyoo-ru/mam_mol/tree/master/hotkey).
