### ISSUE TITLE
WebSockets

### ISSUE THREAD

**Issue by nin-jin** [hyoo-ru/mam_mol#20]
Двухсторонняя синхронизация через сокеты.

**Comment by ar2r13** [comment]
Между кем и кем?

**Comment by nin-jin** [comment]
Между сервером и клиентом. С интерфейсом как у $mol_state_*

**Comment by nin-jin** [comment]
Сейчас этим занимается [$mol_store_socket](https://github.com/hyoo-ru/mam_mol/tree/master/store/socket). По умолчанию он использует для синхронизации сервис [sync.hyoo.ru](https://github.com/hyoo-ru/sync.hyoo.ru) поднятый на хероку.
