### ISSUE TITLE
IE, iOS. Верстка графиков в приложении $mol_chart_demo

### ISSUE THREAD

**Issue by NatalyaBudnikova** [hyoo-ru/mam_mol#202]
**Приложение:** [$mol_chart_demo](http://mol.js.org/#completed/demo=mol_chart_demo)
**Браузеры:**  
        Safari, iOS 9.3.5 (iPad), iOS 10.2.1 (iPhone 5s)
        Microsoft Edge 20.10240.16384.0 (Windows 10, IRBIS TW38)
        IE 11.0.10240.17354 (Windows 10, IRBIS TW38)
**Детали:**

_Шаги воспроизведения:_
1. Запустить приложение $mol_chart_demo

_Ожидаемое поведение_
Графики отображаются корректно

_Текущее поведение_
iOS: 
![img_0405](https://cloud.githubusercontent.com/assets/25827903/25578641/663bfb2c-2e79-11e7-9ff8-64a0587ab3d1.PNG)
![img_0406](https://cloud.githubusercontent.com/assets/25827903/25578647/6b88adfa-2e79-11e7-931a-da29d57d0eda.PNG)
Microsoft Edge:
![9c41c64f38](https://cloud.githubusercontent.com/assets/25827903/25578661/96e24bc8-2e79-11e7-8399-93aadd29a795.jpg)
IE 11: 
![ba2d8493a5](https://cloud.githubusercontent.com/assets/25827903/25578667/a0b488fa-2e79-11e7-889f-dfa7eb483e2f.jpg)

**Comment by JulyJ** [comment]
Проблема акутальна и для IE 11: [215](https://github.com/eigenmethod/mol/issues/215)

**Comment by JulyJ** [comment]
Смотрела на IE 11.0.9600.18763, верстка все равно ползет. Например легенда к графикам:
![selection_960](https://user-images.githubusercontent.com/4419881/29274397-6c055960-8110-11e7-9fec-ac8ab553765d.png)
Смотрела на iOS 10.0.3  в Safari, графики не ресайзяся и отображаются только частично:
![image](https://user-images.githubusercontent.com/4419881/29274502-c4f6f9de-8110-11e7-8219-a574ef8a0e7c.png)

**Comment by nin-jin** [comment]
Поддержка старых браузеров для нас сейчас не актуальна.
