### ISSUE TITLE
Android. Нет скроллинга в приложении $mol_search и $mol_pop_demo

### ISSUE THREAD

**Issue by NatalyaBudnikova** [hyoo-ru/mam_mol#204]
**Приложение:** [$mol_search](http://mol.js.org/#filter/gist=180442153/demo=mol_search_demo), [$mol_pop_demo](http://mol.js.org/#filter/gist=180442153/demo=mol_pop_demo/supply=75BCD15)
**Браузеры:**  
        Chrome 57.0.2987.132, Android 6.0.1 (Samsung)
**Детали:**

_Шаги воспроизведения:_
1. Запустить приложение $mol_search
2. Ввести несколько символов в поле поиска
3. В приложении $mol_pop_demo раскрыть выпадающий список Align

_Ожидаемое поведение_
В выпадающем списке есть скроллинг

_Текущее поведение_
Скроллинга нет
![screenshot_20170502-102416](https://cloud.githubusercontent.com/assets/25827903/25608008/d57107c8-2f21-11e7-9e64-9f1cc0955881.png)
![screenshot_20170502-122123](https://cloud.githubusercontent.com/assets/25827903/25612110/1521be66-2f32-11e7-9ea0-aa87b5fa7f47.png)

**Comment by nin-jin** [comment]
Сейчас скроллинг уже есть:
https://mol.hyoo.ru/#section=components/demo=mol_search_demo
