### ISSUE TITLE
Нет скроллинга в $mol_pop_demo

### ISSUE THREAD

**Issue by NatalyaBudnikova** [hyoo-ru/mam_mol#208]
**Приложение:** [$mol_pop_demo](http://mol.js.org/#filter/gist=180442153/demo=mol_pop_demo/supply=75BCD15)
**Браузеры:**  
        устройства с маленьким разрешением экрана, например iOS 10.2.1 (iPhone 5s)
**Детали:**

_Шаги воспроизведения:_
1. Запустить приложение $mol_pop_demo
2. Выбрать расположение left_top

_Ожидаемое поведение_
Возможно нужно добавить скроллинг, чтобы можно было увидеть результат.

_Текущее поведение_
Нет возможности посмотреть результат приложения
![img_0406](https://cloud.githubusercontent.com/assets/25827903/25611551/25300b52-2f30-11e7-9aca-48b4aa52070d.PNG)

**Comment by JulyJ** [comment]
У меня эта же проблема возникает и в стандартном окне браузера Chromе но ноутбуке:
![selection_682](https://cloud.githubusercontent.com/assets/4419881/25613774/1c9eb1ac-2f38-11e7-8a10-cfadb0dc279f.png)

**Comment by nin-jin** [comment]
Надо будет переработать демо, чтобы переполнения не происходило.

**Comment by nin-jin** [comment]
Демо переработано. Теперь этот компонент сам выбирает куда открываться и прикладнику не нужно выбирать вручную куда его разворачивать.
