### ISSUE TITLE
Android. Выпадающий список высотой на все окно браузера в $mol_select_demo

### ISSUE THREAD

**Issue by NatalyaBudnikova** [hyoo-ru/mam_mol#212]
**Приложение:** [$mol_select_demo](http://mol.js.org/#filter/gist=180442153/demo=mol_select_demo_colors/supply=75BCD15)
**Браузеры:**  
        Chrome 57.0.2987.132, Android 6.0.1 (Samsung)
**Детали:**

_Шаги воспроизведения:_
1. Запустить приложение $mol_select_demo
2. Раскрыть выпадающий список

_Ожидаемое поведение_
Например, как в браузере Internet (тот же Android)
![screenshot_20170502-132056](https://cloud.githubusercontent.com/assets/25827903/25614345/456a7fce-2f3a-11e7-805c-e9d563d643e0.png)

_Текущее поведение_
![screenshot_20170502-130559](https://cloud.githubusercontent.com/assets/25827903/25614311/2494fd74-2f3a-11e7-89dc-c1bbe06c8fee.png)

**Comment by nin-jin** [comment]
Хз, воспроизводится ли ещё. Доступа к тому планшету больше нет.
Проверить можно тут: https://mol.hyoo.ru/#section=components/demo=mol_select_demo_colors
Закрываю пока что, ибо каких-то работ в этом направлении не планируется.
