### ISSUE TITLE
iOS. Не закрывается выпадающий список в $mol_pop_over

### ISSUE THREAD

**Issue by NatalyaBudnikova** [hyoo-ru/mam_mol#213]
**Приложение:** [$mol_pop_over](http://mol.js.org/#filter/gist=180442153/demo=mol_pop_over_demo/supply=75BCD15)
**Браузеры:**  
        Safari, iOS 9.3.5 (iPad), iOS 10.2.1 (iPhone 5s)
**Детали:**

_Шаги воспроизведения:_
1. Запустить приложение $mol_pop_over
2. Открыть выпадающий список 
3. Снять фокус с кнопки, чтобы закрыть выпадающий список (например, нажать на пространство вне кнопки)

_Ожидаемое поведение_
Выпадающий список закрывается

_Текущее поведение_
Выпадающий список не закрывается

**Comment by nin-jin** [comment]
В сафари тап по другому (нефокусируемому) элементу не снимает фокус с текущего элемента. Нужно тапать именно по фокусируемому.

**Comment by nin-jin** [comment]
Сейчас корень $mo_book2 является фокусируемым, так что в реальных приложениях таких проблем быть не должно. Возможно стоит сделать фокусируемым и $mol_page.
