### ISSUE TITLE
Edge, Safari. Верстка бокового меню после перехода из горизонтального в вертикальное положение планшета

### ISSUE THREAD

**Issue by NatalyaBudnikova** [hyoo-ru/mam_mol#218]
**Приложение:** [$mol_text](http://mol.js.org/#filter/gist=180442153/demo=mol_text_demo/supply=75BCD15)
**Браузеры:**  
        Safari, iOS 9.3.5 (iPad)
        Microsoft Edge 20.10240.16384.0 (Windows 10, IRBIS TW38)
**Детали:**

_Шаги воспроизведения:_
1. Запустить приложение $mol_text в горизонтальном положении планшета
2. Закрыть приложение, что бы на экране отобразилось только боковое меню
3. Перевернуть планшет в вертикальное положение

_Ожидаемое поведение_
Верстка не портится, скроллинг бокового меню работает корректно

_Текущее поведение_
Microsoft Edge - меню поднимается на пол экрана вверх и некорректно работает скроллинг
![d45718d492](https://cloud.githubusercontent.com/assets/25827903/25621479/26b66622-2f5a-11e7-8315-ad12059a5d12.jpg)
 
iOS - почти тоже самое, но получше немного чем в Microsoft Edge
![image 4](https://cloud.githubusercontent.com/assets/25827903/25621640/9c80dc70-2f5a-11e7-9574-179296e18afc.png)

**Comment by JulyJ** [comment]
Проверяла на iOS 10.3.3 в Safari:
После смены ориентации планшета с горизонтальной на вертикальную перестает работать скрол по меню навигации.

**Comment by nin-jin** [comment]
Проблема была с виртуализацией. Сейчас используется более надёжное решение, где такой проблемы быть не должно.
