### ISSUE TITLE
Slow scroll of $mol_row

### ISSUE THREAD

**Issue by nin-jin** [hyoo-ru/mam_mol#225]
https://habrahabr.ru/post/330466/#comment_10255960
> В сафари сразу же начинает ужасно тормозить при скроле. Даже когда не в самом конце списка товаров. И нет, скроллбар я не трогаю.

http://toys.hyoo.ru

**Comment by bromzh** [comment]
MacOS Sierra 10.12.5 (16F73), Safari 10.1.1 (12603.2.4)

**Comment by muleronko** [comment]
Проблема репайнта в сафари

**Comment by nin-jin** [comment]
Происходит repaint из-за reflow, который происходит из-за того, что мы добавляем элементы по мере скролла. Решается либо отказом от динамики (что в общем случае невозможно), либо возможно кастомным абсолютным позиционированием элементов.

**Comment by nin-jin** [comment]
Сори, ошибся таском.

**Comment by nin-jin** [comment]
Сейчас для $mol_row выключена виртуализация, то есть рендерится всё сразу. Это должно давать более отзывчивый скролл, но долгое появление при большом числе элементов. Если будем реализовывать его виртуализацию, то будем думать о том, чтобы минимизировать reflow. Но тут есть определённые сложности:  https://slides.hyoo.ru/#slides=https%3A%2F%2Fnin-jin.github.io%2Fslides%2Fvirt%2F/slide=43
