### ISSUE TITLE
Не работает прокрутка над картинкой Safari

### ISSUE THREAD

**Issue by muleronko** [hyoo-ru/mam_mol#242]
При заходе с safari 10.1.2 в приложение $mol_app_habhub, не работает прокрутка по наведению на картинку.

**Comment by nin-jin** [comment]
Причина по всей видимости в использовании `object` для отображения картинок.

**Comment by PavelZubkov** [comment]
<img width="953" alt="image" src="https://user-images.githubusercontent.com/23323484/190491258-bca5fc62-a537-434d-8483-785fadb71db2.png">

Только над такими штуками удалось воспроизвести. При скролле колесом, один раз получилось воспроизвести.
Тачпадом получается всегда - им нужно горизонтальный сколл попробовать сдвинуть, тогда начинается залипать и тачпадом и колесом

**Comment by nin-jin** [comment]
Там раньше все картинки рендерились объектом, теперь по возможности рендерится через img, так что такой проблемы быть не должно.

**Comment by PavelZubkov** [comment]
этот закрыть можно уже?

**Comment by nin-jin** [comment]
Думаю да.
