### ISSUE TITLE
Не всегда одинаковый порядок ключей в mem_key + object

### ISSUE THREAD

**Issue by zerkalica** [hyoo-ru/mam_mol#258]
Ключи в объекте не упорядоченны, нельзя гарантировать порядок записи их в строку в JSON.stringify.
Может в случае объектов, использовать что-то вроде этого?

```js
function getKeyFromObj(params: Object): string {
    const keys = Object.keys(params)
        .sort()

    let result = ''
    for (let i = 0; i < keys.length; i++) {
        const key = keys[i]
        const value = params[key]
        result += `.${key}:${typeof value === 'object' ? JSON.stringify(value) : value}`
    }

    return result
}
```

**Comment by nin-jin** [comment]
Надо тестить производительность, боюсь кастомный сериализатор будет сильно медленней.

**Comment by nin-jin** [comment]
Как вариант - использовать массивы в качестве ключей:

```
cell( [ row , cell ] : [ number , number ] ) { ... }
```

```
this.cell([ 'row' && 1 , 'cell' && 2 ])
```

**Comment by zerkalica** [comment]
или как в Map ``` [Key, Value][] ```, но по-любому точность важнее.

**Comment by nin-jin** [comment]
Кастомный сериализатор сильно медленней получается, поэтому сейчас используется либо JSON.stringify для JSON значений, либо сам объект в остальных случаях.

Думаю нет особой проблемы формировать объекты с постоянным порядком ключей - это так же даёт и увеличение перфоманса. К тому же актуальная спека гарантирует порядок ключей, а это значит, что логика может быть на него завязана и будет странно, если мы начнём их приводить к единому порядку под капотом.
