### ISSUE TITLE
Demo $mol_app_habhub_demo, при прокрутке компонент не выходит из режима обновления в Firefox

### ISSUE THREAD

**Issue by AlexRadch** [hyoo-ru/mam_mol#288]
Если сделать прокрутку любой статьи примерно на треть или больше, то просмотр входит в режим внутреннего обновления (синие бегущие полоски в фоне) и не выходит из него пока не поднимешься обратно примерно выше трети статьи.

![screenshot_3](https://user-images.githubusercontent.com/6407980/32666900-9f7f6754-c66b-11e7-93aa-c3f881c3f95c.png)

Протестируйте ваши демонстрационный программы в Firefox. Это не единственная ошибка.

**Comment by nin-jin** [comment]
Это появляется компонент показа комментариев, но индикатор загрузки не должен вылезать за пределы того компонента.

**Comment by nin-jin** [comment]
Тут уже не воспроизводится: https://habhub.hyoo.ru/#author=nin-jin/repo=HabHub/article=39
