### ISSUE TITLE
Demo $mol_app_calc_demo, циклическая ссылка запрещает дальнейщее изменение этой ячейки в Firefox

### ISSUE THREAD

**Issue by AlexRadch** [hyoo-ru/mam_mol#289]
Если сделать циклическую ссылку, то после этого редактирование этой ячейки перестает работать в Firefox

![screenshot_4](https://user-images.githubusercontent.com/6407980/32667590-a9bc16fc-c66d-11e7-94eb-690f4cece4c1.png)

Как видите хочу изменить циклическую ссылку на число 1111, но изменение не работает.

Протестируйте ваши демонстрационные программы в Firefox. Это не единственная ошибка.

**Comment by nin-jin** [comment]
У меня на 56 не вспроизводится. Можете прислать ссылку на вашу таблицу?

**Comment by AlexRadch** [comment]
В первой ячейке пишите =A1 получается циклическая ссылка после этого не
значение невозможно поменять. Например на любое число или на любую строку.

11 нояб. 2017 г. 12:30 AM пользователь "nin-jin" <notifications@github.com>
написал:

**Comment by nin-jin** [comment]
Раньше там была кнопка открывающая боковое меню. Теперь боковое меню открывается обычным скроллингом. А кнопка убрана  и теперь название страницы можно выделять.

**Comment by nin-jin** [comment]
Тестовая страница: https://calc.hyoo.ru/#title=self%20reference/A1=%3DA1
Сейчас уже не воспроизводится.
