### ISSUE TITLE
Невозможно выделить имя любой демо программы

### ISSUE THREAD

**Issue by AlexRadch** [hyoo-ru/mam_mol#292]
Невозможно выделить имя любой демо программы. Например $mol_app_calc_demo. Выделение постоянно сбрасывается. Так не должно быть.

![screenshot_1](https://user-images.githubusercontent.com/6407980/32768006-88f1071a-c948-11e7-8efe-25c490d3e525.png)

Например `$mol демонстрации` выделяется, а `$mol_app_calc_demo` нет.

**Comment by nin-jin** [comment]
Это происходит из-за того, что клик по заголовку по умолчанию переносит фокус на сайдбар. Если он скрыт, то это приводит к его появлению.

**Comment by nin-jin** [comment]
Раньше там была кнопка открывающая боковое меню. Теперь боковое меню открывается обычным скроллингом. А кнопка убрана и теперь название страницы можно выделять.
