### ISSUE TITLE
$mol_date_demo: нельзя выбрать месяц и год

### ISSUE THREAD

**Issue by AlexRadch** [hyoo-ru/mam_mol#298]
Выбор даты должен позволять изменить месяц и год

![screenshot_6](https://user-images.githubusercontent.com/6407980/32773606-47b9c6b0-c95c-11e7-9e3b-e1adb3169352.png)

Желательно сегодняшнюю дату как то выделять, например фоном.

Строка с датой вообще ведет себя неадекватно! Огромное число ошибок!

**Comment by nin-jin** [comment]
Месяц и год легко изменить - просты ставим курсор на месяц или год и редактируем. Но да, можно добавить стрелочки для быстрого перехода к соседним месяцам и годам. А в чём неадекватность и огромное число ошибок?

**Comment by nin-jin** [comment]
Стрелочки добавил: https://mol.hyoo.ru/#section=components/demo=mol_date_demo
