### ISSUE TITLE
Дырявая песочница

### ISSUE THREAD

**Issue by cevek** [hyoo-ru/mam_mol#303]
Этим кодом не спастись от зловредов
```ts
try {
    Function.prototype.constructor = undefined
    return func()
}
```
Есть куча способов сделать new Function
от самых простых
```ts
new (async function() {}).constructor('alert("Haha")')()
new (function *() {}).constructor('alert("Haha")')().next()
```
до более сложных c iframe из документа которого можно достать все что хочешь

**Comment by nin-jin** [comment]
От этих двух добавил защиту:
http://mol.js.org/app/calc/#A1=%3Dnew%20%28async%20function%28%29%20%7B%7D%29.constructor%28'alert%28%22Haha%22%29'%29%28%29/A2=%3Dnew%20%28function%20*%28%29%20%7B%7D%29.constructor%28'alert%28%22Haha%22%29'%29%28%29.next%28%29/A3=%3D

Как ещё можно создать функцию? И как вы собираетесь создать фрейм без доступа к document?

**Comment by cevek** [comment]
Я не понимаю выгоды от этой песочницы, она же может все поломать в твоем запускаемом контексте
ну типа
```js
eval('1..__proto__.constructor.isNaN = ()=>true')
eval('({}).__proto__.constructor.defineProperty = ()=>{}')
```

**Comment by cevek** [comment]
После твоего фикса конструкторы генераторов и async функций не возвращаются на место.

**Comment by cevek** [comment]
Если в window есть стринговое свойство `window['a.b']` то при eval вылетает ошибка

**Comment by cevek** [comment]
Вообщем идея хорошая, но надо поработать над всеми прототипами доступными из этой песочницы

**Comment by nin-jin** [comment]
Да, я пробовал возвращать конструкторы, но там что-то перемудрили с ними. Их и удалить-то еле получилось. Для этого пришлось стирать их изнутри песочницы, через импортированный Object.

Но да, код может поломать доступные ему объекты. Тут я не знаю как можно обезопасить, кроме как создавать по отдельному фрейму на каждый запуск и не давать доступа ни к чему из родительского.

Вы лучше приводите примеры в http://mol.js.org/app/calc/ а то понять что вы имеете ввиду не очень получается.

**Comment by cevek** [comment]
Дима, на ты, на ты, мы с тобой знакомы давно уже :)
Вообще я думаю нужно для всех свойств всех доступных прототипов нужно сделать writable: false, а после возвращать на место все как было.
Ну и плюс закрыть методы которые могут менять дескрипторы

**Comment by cevek** [comment]
Что можно получить из js без использования конструктора
```
String,
Number,
Boolean,
Array,
Error,
RangeError,
ReferenceError,
SyntaxError,
TypeError,
RegExp,
Function,
AsyncFunction,
GeneratorFunction,
Object,
Promise,
Symbol
```
Дополни если что еще знаешь

**Comment by nin-jin** [comment]
Это официальный репозиторий, так что тут только на вы :-)
Боюсь слишком много всего нужно менять и откатывать. Я думаю лучше создать скрытый фрейм и в нём капитально позаблокировать всё.
Но эти конструкторы - пол беды. Если передавать в сендбокс объекты, то и через их прототипы можно делов наворотить. То есть от "поломки" защититься в общем случае никак. Но можно защититься от выполнения недозволенных апишек.

**Comment by cevek** [comment]
а что поменяется то? ты передашь объект в iframe, а он там его и его прототипы также сломает как угодно. Тут наверное стоит вопрос как не поломать нативные вещи

**Comment by nin-jin** [comment]
Так я и говорю, что от поломки не защититься. Кому надо защититься от поломок - будут запускать песочицу в воркере и общаться с ней, соответственно, через сообщения.

**Comment by cevek** [comment]
На самом деле можно решить проблему проще, все поломки делаются через прототип, соответсвенно если закрыть __proto__ и переопределение дескрипторов то чтобы нибудь сломать будет практически нереально

**Comment by nin-jin** [comment]
И как же закрыть __proto__?

**Comment by cevek** [comment]
Накидал рабочую примерную версию, позже сделаю пулл реквест
```js

var generatorFunction = function*() {
    return 1;
};
var asyncFunction = async function() {
    return 1;
};
var original = {
    defineProperty: Object.defineProperty,
    defineProperties: Object.defineProperties,
    freezeConstructorsAndProto: [
        String,
        Number,
        Boolean,
        Array,
        Uint8Array,
        Int8Array,
        Uint8ClampedArray,
        Uint16Array,
        Int16Array,
        Uint32Array,
        Int32Array,
        Float32Array,
        Float64Array,
        ArrayBuffer,
        Date,
        Error,
        RangeError,
        ReferenceError,
        SyntaxError,
        TypeError,
        RegExp,
        Function,
        Object,
        Proxy,
        Reflect,
        Map,
        WeakMap,
        Set,
        WeakSet,
        Promise,
        Symbol,
        generatorFunction.__proto__,
        asyncFunction.__proto__,
    ].map(c => ({ ctor: c, descriptors: null, prototypeDescriptors: null })),

    disableObjectDescriptors: [
        { object: Function.prototype, props: ['constructor'] },
        { object: generatorFunction.__proto__, props: ['constructor'] },
        { object: asyncFunction.__proto__, props: ['constructor'] },
        {
            object: Object,
            props: [
                'getPrototypeOf',
                'setPrototypeOf',
                'defineProperty',
                'defineProperties',
                'freeze',
                'seal',
                'preventExtensions',
            ],
        },
        {
            object: Object.prototype,
            props: ['__proto__', '__defineGetter__', '__defineSetter__', '__lookupGetter__', '__lookupSetter__'],
        },
    ],
};

function disableDescriptors(o) {
    var originalDescriptors = Object.getOwnPropertyDescriptors(o);
    var newDescriptors = {};
    Object.keys(originalDescriptors).forEach(key => {
        var oDescriptor = originalDescriptors[key];
        if (o === Array.prototype && key === 'length') return;
        if (oDescriptor.writable) {
            newDescriptors[key] = { configurable: true, writable: false, value: oDescriptor.value };
        }
    });
    original.defineProperties(o, newDescriptors);
    return originalDescriptors;
}

function patch() {
    original.freezeConstructorsAndProto.forEach(c => {
        c.descriptors = disableDescriptors(c.ctor);
        c.prototypeDescriptors = c.ctor.prototype && disableDescriptors(c.ctor.prototype);
    });

    original.disableObjectDescriptors.forEach(p => {
        p.props.forEach(prop =>
            original.defineProperty(p.object, prop, { writable: false, value: undefined, configurable: true })
        );
    });
}

function restore() {
    original.freezeConstructorsAndProto.forEach(c => {
        original.defineProperties(c.ctor, c.descriptors);
        if (c.prototypeDescriptors) {
            original.defineProperties(c.ctor.prototype, c.prototypeDescriptors);
        }
    });
}
```

**Comment by nin-jin** [comment]
Сюда приходит 2 массива:
```
original.defineProperties(o, newDescriptors);
```

**Comment by nin-jin** [comment]
Прототип Array кривой получается. Я думаю в сторону полноценной песочницы в воркере, где всё заморожено и у исполняющейся функции не может быть побочных действий.

**Comment by cevek** [comment]
Можешь подробнее описать, что там с массивами, не очень понял
А в вебворкере замораживать даже ничего не надо, создал использовал его и выбросил - доступа там вообще же ни к чему же практически нет

**Comment by nin-jin** [comment]
В Array.prototype появляются числовые ключи со значениями в виде имён методов.
Создавать вебворкер на каждый чих - дорого слишком. А вот создать в нём песочницу и исполнять в нём чистые функции - самое оно.

**Comment by nin-jin** [comment]
Михаих Ермишин предлагал такой код:
```
async function safe_eval(code) {
  const embedded_code =
    `function __$code(){${code}}\
    postMessage(__$code());\
    onmessage = function(e){console.log(e);}`
  const blob = new Blob([embedded_code], {
    type: "text/javascript"
  });

  const w = new Worker(window.URL.createObjectURL(blob));
  let result = undefined;
  return await new Promise(resolve => w.onmessage = resolve);
}
safe_eval('return 5').then(e => console.log(e.data))
```

**Comment by nin-jin** [comment]
Я думаю сделать общение с воркером через Proxy по аналогии с $mol_rpc: https://github.com/eigenmethod/mol/blob/master/rpc/client/frame/frame.ts#L46

**Comment by nin-jin** [comment]
Сделал защищённую песочницу в отдельном фрейме, где гайки закручены по максимуму. Единственная уязвимость - возможность сделать бесконечный цикл и всё повесить.

**Comment by nin-jin** [comment]
Написал об этом статью: https://habhub.hyoo.ru/#author=nin-jin/repo=HabHub/article=19
Новых дырок пока не обнаружено.
