### ISSUE TITLE
При сборке веб-паком module.exports в web.esm.js является undefined

### ISSUE THREAD

**Issue by PomanoB** [hyoo-ru/mam_mol#316]
Падает на строчке

var $ = ( typeof module === 'object' ) ? Object.setPrototypeOf( module['export'+'s'] , self ) : self

А если подключать web.js(в package.json заменить "browser": "web.esm.js" на "browser": "web.js",) то работает нормально.

**Comment by nin-jin** [comment]
Так и сделали.
