### ISSUE TITLE
Change detection issues

### ISSUE THREAD

**Issue by nin-jin** [hyoo-ru/mam_mol#319]
> Убедился, что под Node.js 11 (v11.7.0) пересборка по Ctrl+R по прежнему не работает (даже для "chokidar": "^2.1.0")
> Убедился, что для "chokidar": "^2.0.3" пересборка по Ctrl+R по прежнему не работает (даже для Node.js 8)

**Comment by zerkalica** [comment]
Актуально еще?

**Comment by nin-jin** [comment]
Хороший вопрос, вспомнить бы ещё кто жаловался на это.

**Comment by nin-jin** [comment]
Несколько раз фиксили это дело. Думаю уже не актуально. Да и ноды старые.
