### ISSUE TITLE
Не работают контексты для компонент page-контейнеров

### ISSUE THREAD

**Issue by zerkalica** [hyoo-ru/mam_mol#324]
Если $my_a рендерит не сам $my_b, его pages, то $my_b не получит определенный в $my_a контекст.

```ts
	export class $my_a $.$my_a {
		context_sub() {
			return this.$.$mol_ambient({
				$my_domain: $my_mock,
			})
		}
                sub() {
                   return [...this.My_b().pages()]
                }
	}

	export class $my_b $.$my_b {
                pages() {
                   this.$.$my_domain instanceof $my_mock // false
                }
	}

```

**Comment by nin-jin** [comment]
Не очень понятно написано. Насколько я понимаю, некий $my_c берёт из $my_a $my_b и рендерит в себя. А так как контексты наследуются через иерархию рендеринга, то $my_a в неё получается не попадает.

**Comment by nin-jin** [comment]
Возможно стоит ввести 2 разных контекста:
1. контекст зависимостей, наследующийся через иерархию владения. 
2. контекст рендеринга, наследующийся через иерархию рендеринга.

**Comment by zerkalica** [comment]
> Не очень понятно написано. Насколько я понимаю, некий $my_c берёт из $my_a $my_b и рендерит в себя. А так как контексты наследуются через иерархию рендеринга, то $my_a в неё получается не попадает.

a рендерит c из b.pages, но не сам b, поэтому контекст в b не тот, который в a

**Comment by zerkalica** [comment]
> Возможно стоит ввести 2 разных контекста:
> 
> 1. контекст зависимостей, наследующийся через иерархию владения.
> 2. контекст рендеринга, наследующийся через иерархию рендеринга.

зачем вообще контекст рендеринга, владения не достаточно?

**Comment by nin-jin** [comment]
Например, чтобы любой компонент мог предоставлять/использовать знания о вьюпорте. За счёт этого, например, $mol_ist  узнаёт о том, колько ему надо отрендерить, чтобы заполнить $mol_scroll.

**Comment by nin-jin** [comment]
В текущей реализации контекст рендеринга выпилен, остался только контекст владения, так что описанная проблема воспроизводиться не должна.
