### ISSUE TITLE
$mol_app_questions: ограничить число вопросов

### ISSUE THREAD

**Issue by nin-jin** [hyoo-ru/mam_mol#344]
Сейчас выводятся 10000 вопросов. Это приводит к тому, что когда пользователь начинает баловаться со скроллингом, интерфейс подвисает в попытке отрендерить много вопросов. А на stackoverflow api быстро кончаются лимиты и приложением становится невозможно пользоваться.

Предлагаю ограничить вывод до 1000 вопросов.

**Comment by zerkalica** [comment]
А нельзя просто не давать скролить, дергая за ползунок, а только колесиком или тормозить скрол, что б нельзя было за раз проскролить 10к айтемов?

**Comment by nin-jin** [comment]
Будут жалобы, что скроллинг не работает вообще.

**Comment by zerkalica** [comment]
А если так?

до 1к - выводим скрол как есть
> 1к и элементы произвольной высоты - тормозим скролл
> 1к и элементы фиксированной высоты - рассчет позиции по формуле и подгрузка по отпусканию скрола

**Comment by nin-jin** [comment]
Да не нужно никому больше 1к. Не вижу смысла вообще думать на эту тему. Задача ленивого рендера в данном случае - чтобы страница открылась за разумное время, если в списке вдруг оказалось 10к. А не для того, чтобы со всеми этими 10к было комфортно работать.

**Comment by zerkalica** [comment]
Я про защиту от дурака в случае 10к

**Comment by nin-jin** [comment]
А зачем от дурака защищаться?

**Comment by zerkalica** [comment]
есть же возможность 10к отобразить и дернуть ползунок, пользователь обязательно дернет.
практика же, сколько уже дернуло за этот ползунок.

**Comment by nin-jin** [comment]
Ты так и не объяснил зачем.

**Comment by zerkalica** [comment]
Что б дурак не завесил браузер и из-за него не забанили подсеть из которой он заддосит сайт, дернув ползунок.

**Comment by nin-jin** [comment]
Поэтому в этой задаче мы и ограничиваем 1к.

**Comment by zerkalica** [comment]
В самом скроле нельзя как-то ограничить?

**Comment by nin-jin** [comment]
Это будет деструктивная оптимизация.

**Comment by zerkalica** [comment]
не обязательно, можно в подгружаемый буфер, как в телеге

**Comment by nin-jin** [comment]
И будут те же жалобы - скроллбар скачет от курсора.

**Comment by zerkalica** [comment]
Практика телеги показывает, что нет. Без экспериментов твоё утверждение голословно.

**Comment by nin-jin** [comment]
Практика показывает, что текущее поведение $mol_list волнует не реальных пользователей, а любителей поискать недостатки в реализации.

**Comment by zerkalica** [comment]
Без слепого тестирования не о чем.

**Comment by nin-jin** [comment]
Ограничил в 1к. Всё-равно когда мотаешь туда-сюда, быстро выедаются лимиты и загрузка совсем падает.
