### ISSUE TITLE
mol_taxon не работает - апи внешнее не существует

### ISSUE THREAD

**Issue by zerkalica** [hyoo-ru/mam_mol#359]
надо какой-то мок или жсон рядом положить

http://127.0.0.1:8080/mol/app/taxon/index.html

Т.к. ссылка http://justine.saprun.com:8000/sap/opu/odata/sap/ZTRNF_TEST_DATA_SRV/TRNF_TREESet?$format=json не существует

**Comment by nin-jin** [comment]
Надо объединить его с $mol_app_taxon_demo
Или вообще выпилить. Это не очень реалистичная демка. Сделана была лишь для того, чтобы показать газпромнефти что мы умеем быстро рендерить таблички с иерархией.

**Comment by nin-jin** [comment]
Выпилили.
