### ISSUE TITLE
Улучшить вывод ошибок в компонентах

### ISSUE THREAD

**Issue by zerkalica** [hyoo-ru/mam_mol#361]
Что б не пестрело Forbidden во всех местах, хотя ошибка одна.
http://127.0.0.1:8080/mol/app/users/#query=wz

![image](https://user-images.githubusercontent.com/274786/64413237-cd08f200-d099-11e9-9a74-32f1e7052e67.png)

**Comment by nin-jin** [comment]
Ну а что ты предлагаешь?

**Comment by zerkalica** [comment]
Показать ошибку в самом большом компоненте.
В остальных проверять, что ошибка уже показана пользователю и текст не выводить, только бленду или как-то сворачивать текст.

**Comment by zerkalica** [comment]
Еще кнопка с текстом Forbidden внизу, а бленды на ней не видно

**Comment by nin-jin** [comment]
Как ты предлагаешь определять какой компонент самый большой?

У меня есть такая мысль - показать сломанные виджеты сломанными, а ошибку писать как отдельную нотификацию.

**Comment by zerkalica** [comment]
> Как ты предлагаешь определять какой компонент самый большой?

minimal_width, не пойдет?

> У меня есть такая мысль - показать сломанные виджеты сломанными, а ошибку писать как отдельную нотификацию.

Главное что б пользователь контекст не потерял, когда, бац, все стирается и рисуется модалка.

**Comment by zerkalica** [comment]
Еще такой вывод ошибок - сильно может сломать верстку, что если помечать как-то компонент для вывода ошибок и если любой дочерний сбойнул - выводить в верхний по иерархии, в котором есть пометка.

![image](https://user-images.githubusercontent.com/274786/64424317-70193600-d0b1-11e9-9b9f-f239f829e2f8.png)

**Comment by nin-jin** [comment]
Через контекст должна быть возможность задать свой обработчик ошибок.

**Comment by zerkalica** [comment]
Нужны примеры

**Comment by nin-jin** [comment]
Нужно проектирование.

**Comment by zerkalica** [comment]
Вот это могло бы помочь, но как сделать хз:

> У меня есть такая мысль - показать сломанные виджеты сломанными, а ошибку писать как отдельную нотификацию.

**Comment by nin-jin** [comment]
Для начала надо сделать компонент вывода нотификаций :-)

**Comment by zerkalica** [comment]
![image](https://user-images.githubusercontent.com/274786/67327810-339a8000-f521-11e9-99cd-b1dd4c60a652.png)

**Comment by nin-jin** [comment]
Если не устраивает поведение по умолчанию (отображение ошибок в нескольких вложенных компонентах), то можно дёрнуть общие для них свойства уровнем выше, что приведёт к падению выше по дому.

Если хочется отличной от дефолтной визуализации, то ошибку можно перехватить через try-catch и нарисовать что душа пожелает.

Пример на http.hyoo.ru: https://github.com/hyoo-ru/http.hyoo.ru/commit/6f80cfbdd021b6f06e69cc8658e9222e4c1bcb5a

[![image](https://user-images.githubusercontent.com/442988/107363861-ce8ae500-6aeb-11eb-9da8-651a8001ec0b.png)](http://http.hyoo.ru/#uri=http%3A%2F%2Fexample.org%2F)

**Comment by nin-jin** [comment]
В будущем, можно подумать над такой эвристикой: если два разных компонента падают с одной и той же ошибкой, то ищется их ближайший общий родитель и в него эта ошибка прокидывается автоматически.
