### ISSUE TITLE
$mol_app_supplies, $mol_app_users, $mol_app_portal: не видно символов в инпуте

### ISSUE THREAD

**Issue by zerkalica** [hyoo-ru/mam_mol#362]
http://mol.js.org/app/users/#query=wz

Белый текст на белом фоне.

![image](https://user-images.githubusercontent.com/274786/64413430-253ff400-d09a-11e9-807c-c895a36be8d7.png)

**Comment by nin-jin** [comment]
Косяк с темами. Надо вместо цвета "поле" сделать отдельную тему "поле".

**Comment by nin-jin** [comment]
Та же проблема у чекбокса в $mol_app_supplies

**Comment by nin-jin** [comment]
В новом дизайне проблемы больше нет.
