### ISSUE TITLE
$mol_app_issues: Запрос не ожидает окончания ввода и отправляется при первом же введенном символе

### ISSUE THREAD

**Issue by zerkalica** [hyoo-ru/mam_mol#371]
http://127.0.0.1:8080/mol/app/issues

Либо дебонс вернуть, либо сделать отправку запроса по кнопке и по-enter.

**Comment by nin-jin** [comment]
Лучше по энтеру, конечно. Ещё было бы не плохо автодополнение прикрутить.

**Comment by zerkalica** [comment]
Дебонс то может вернешь? Он же нужен в автодополнении и подобных штуках

**Comment by nin-jin** [comment]
Если сервер не справляется с нагрузкой, то именно в этом месте и надо вставлять дебонс. Но лучше сделать так, чтобы сервер справлялся с нагрузкой, чтобы подсказки отрабатывали максимально быстро.

**Comment by zerkalica** [comment]
ну да, дебонс то опциональный вернуть почему не хочешь? по-умолчанию пусть будет отключен.

**Comment by nin-jin** [comment]
Он вносит вредную асинхронность.

**Comment by zerkalica** [comment]
А если это по ui надо или что б сервер не ддосить?

**Comment by nin-jin** [comment]
Добавлять тормоза по ui?
Про сервер я выше ж написал: https://github.com/eigenmethod/mol/issues/371#issuecomment-528895324

**Comment by zerkalica** [comment]
Как вставить дебонс то? нужен хелпер или раскомментить код в mol_string

**Comment by nin-jin** [comment]
Сделать его ручками в месте запроса данных.

**Comment by zerkalica** [comment]
Хелпер то можно дать, что б с нуля не делать

**Comment by nin-jin** [comment]
Ну да, можно.

**Comment by nin-jin** [comment]
Это приложение переехало на https://compare.github.hyoo.ru/
И там сделано добавление через саггест.
