### ISSUE TITLE
Собрать и вывести все песочные проекты mol в левое меню, как сейчас демки.

### ISSUE THREAD

**Issue by zerkalica** [hyoo-ru/mam_mol#373]
Сложно тестить и выискивать эти приложения.

#334

**Comment by nin-jin** [comment]
Я думаю все эти проекты надо либо выпилить, либо сделать полноценный релиз в $hyoo.

**Comment by zerkalica** [comment]
т.е. перенести mol_app в hyoo? и на mol.js.org разместить ссылку?

**Comment by nin-jin** [comment]
Не так грубо, но да.
На mol.js.org уже есть ссылка на showcase.hyoo.ru

**Comment by nin-jin** [comment]
Завёл для этого проект: https://github.com/orgs/hyoo-ru/projects/1

**Comment by zerkalica** [comment]
> На mol.js.org уже есть ссылка на showcase.hyoo.ru
Нужна навигация и привязка ui к сорцам, также как в mol

**Comment by nin-jin** [comment]
Ага, но это должно быть в самих приложениях.

**Comment by nin-jin** [comment]
Все приложения сейчас доступны тут: https://apps.hyoo.ru/
Домашняя страница переехала на https://mol.hyoo.ru/ - там теперь не только галерея компонент и приложений, но другие релевантные ресурсы.
Во всех приложениях уже добавлена ссылка на их репозиторий.
