### ISSUE TITLE
$mol_popup. Всплывающие окна

### ISSUE THREAD

**Issue by adaptmen** [hyoo-ru/mam_mol#391]
# Реализовать всплывающие окна с разными опциями :

* Закрытие,
* Закрытие при клике вне попапа,
* Полноэкранный режим и выход из него,
* Фиксация позиции попапа,
* Ресайз попапа,
* Попап с тенью (overlay),
* Любой попап поверх всего(не fixed, но должен поддерживать перемещение к родителю при scroll, причём если родитель начинает выходить из области просмотра, попап ищет место, чтобы полностью показать себя, если места мало - уменьшает свои размеры под всё оставшееся место)

# Если несколько попапов:

* Закрытие при клике вне попапа, если такая опция активна, закрывает последний открытый,
* Для попапов с тенью должна быть возможность не ставить тень всем попапам, а отображать только над одной тенью

**Comment by nin-jin** [comment]
Кажется тут перечислено слишком много разных ответственностей. В частности, часть из них уже реализована в [$mol_pop](https://github.com/eigenmethod/mol/tree/master/pop).

Для каких целей вы планируете использовать попапы? Возможно этих целей лучше было бы достичь иными способами.

**Comment by adaptmen** [comment]
Нужны вариации модальных окон, которые в свою очередь являются попапами. Мало знаком с mol, сейчас трудно представить адекватную реализацию

**Comment by zerkalica** [comment]
С конкретными бизнес-задачами бы ознакомится, не факт, что попапы нужны вообще. 

Дизайнеры их часто пихают по инерции, потому что с незапамятных времен так повелось. Они плохо на мобилки адаптируются. Модалки блокируют интерфейс, особенно иерархические. В попапах со временем требуется слишком много кастома. 

Я могу накидать кучу других вариантов из реальной не-mol практики. Например, попап масштабируется по размеру экрана с отступами от краев или по-контенту, или по width масштабируется, а по height адаптируется под контент или фиксирован. Ни один из существующих попапов нам не подошел, потому что царь и бог дизайнер - художник и так видит.

В философии mol - делать один раз под все разрешения экранов без media-query. Стаковый интерфейс, выезжающие панели, гармошки, многое делается в mol_book, попап сложно вписать сюда.

**Comment by nin-jin** [comment]
Описанный тут компонент не вписывается в философию дизайна $mol.

- Предпочтительнее использовать $mol_book2, который не блокирует весь интерфейс вырывая пользователя из контекста, а открывает дополнительные панели рядом, расширяя текущий контекст.
- Также важен и вопрос производительности, ведь открытие кучи попапов приводит в формированию большого DOM дерева и снижению скорости работы. Если допустима потеря контектса, то предпочтительнее отрендерить лишь те страницы, что хотелось показать в попапе, без тех, что он закрыл бы.
- В случае мелких попапов с привязкой к компоненту можно использовать $mol_pop. Но и ему стоит предпочесть дополнительную страницу в $mol_book2, если содержимое достаточно объёмно - это куда комфортней при работе с мобилки.
- Тем не менее $mol не ограничивает от создания кастомного $acme_popup,  который реализует любую хотелку. Это сравнительно не сложно. Но не в рамках проекта $mol, предлагающего универсальные кирпичики, использование которых форсирует лучшие практики.
