### ISSUE TITLE
Синхронизация локализаций для всех языков

### ISSUE THREAD

**Issue by gituser3000** [hyoo-ru/mam_mol#407]
Сейчас для английского языка $mol автоматически создает и поддерживает файлы локализации. Т.е добавляет новые ключи, удаляет старые.
Вот так указывается английский перевод :
@ \Perimeters
Рядом генерируется файл с указанным переводом для английского языка.

Для других языков такого механизма нет, что странно.

Предлагаю в приложении дать возможность перечислить имеющиеся языки и для них автоматически генерировать и синхронизировать ключи по аналогии с английским языком. При этом для других языков перевод уже указывается непосредственно в файле перевода, а не в .tree

Это даст нам синхронизированные локали среди всех языков

**Comment by timeshift92** [comment]
думаю, теперь надо как-то указывает какие языки генерит, значить нужен какой-то начальный конфиг

**Comment by zerkalica** [comment]
Суть мола - меньше конфигов, лучше детектить по уже имеющимся файлам локалей

**Comment by nin-jin** [comment]
> лучше детектить по уже имеющимся файлам локалей

Так сейчас и происходит. Нет смысла генерировать русскую локаль, если нет ни одного перевода на русский.

**Comment by nin-jin** [comment]
Я добавил, чтобы лишние ключи исключались из бандлов с текстами.
При этом если какого-то ключа не хватает, то в браузере пишется варнинг и подгружается английский бандл в качестве фолбэка.
