### ISSUE TITLE
Сборщик пересобирает проект при изменении в любых файлах

### ISSUE THREAD

**Issue by gituser3000** [hyoo-ru/mam_mol#420]
По идее должен пересобираться только при изменении файлов, влияющих на бандл

**Comment by nin-jin** [comment]
Надо сделать, чтобы сборщик отслеживал только те файлы, что нужны для открытых в браузере бандлов.

**Comment by nin-jin** [comment]
Эта проблема вроде бы сейчас уже решена.
Тестовая страница держит сокет соединение, которое удерживает список файлов от которых зависят бандлы. При изменении файлов, страница перезагружается, что приводит к сборке бандлов зависящих от изменённых файлов.
