### ISSUE TITLE
Некорректно работает типизация для некоторых компонентов

### ISSUE THREAD

**Issue by gituser3000** [hyoo-ru/mam_mol#424]
<= active_page_link $mol_link
компилируется в
.....
})( new this.$.$mol_link(  ) )

Для $mol_link go to definition (ctrl + click) не отрабатывает. Это препятствует корректной работе плагина для некоторых компонентов

**Comment by nin-jin** [comment]
Не понятно почему типизация отваливается, если к `$mol_ambient_context` примерживается `typeof $.$$`.

**Comment by nin-jin** [comment]
С переработанными контекстами такой проблемы уже нет.
