### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by jgluhov** [hyoo-ru/mam_mol#43]
# List of undocumented or not translated resources.

## Flow

- [ ] Log (https://github.com/eigenmethod/mol/tree/master/log)  

## Collections
- [ ] Range (https://github.com/eigenmethod/mol/tree/master/range)
- [ ] Set (https://github.com/eigenmethod/mol/tree/master/set)
- [x] Dict (https://github.com/eigenmethod/mol/tree/master/dict)
- [ ] Maybe (https://github.com/eigenmethod/mol/tree/master/maybe)

## State modules
- [x] Arg (https://github.com/eigenmethod/mol/tree/master/state/arg)
- [ ] Local (https://github.com/eigenmethod/mol/tree/master/state/local)
- [ ] Session (https://github.com/eigenmethod/mol/tree/master/state/session)
- [ ] History (https://github.com/eigenmethod/mol/tree/master/state/history)
- [ ] Stack (https://github.com/eigenmethod/mol/tree/master/state/stack)

## Math
- [ ] Graph (https://github.com/eigenmethod/mol/tree/master/graph)
- [ ] Unit (https://github.com/eigenmethod/mol/tree/master/unit)
- [ ] MergeDict (https://github.com/eigenmethod/mol/tree/master/merge/dict)

## Testing
- [x] Test (https://github.com/eigenmethod/mol/tree/master/test)
- [ ] Stub (https://github.com/eigenmethod/mol/tree/master/stub)

## API
- [ ] Exec (https://github.com/eigenmethod/mol/tree/master/exec)
- [ ] File (https://github.com/eigenmethod/mol/tree/master/file)
- [ ] Window (https://github.com/eigenmethod/mol/tree/master/window)

**Comment by nin-jin** [comment]
Не актуально. Нужно проводить новую ревизию кодовой базы. Будет выполняться по мере подготовки туториалов.
