### ISSUE TITLE
Json <=> Tree

### ISSUE THREAD

**Issue by ethernidee** [hyoo-ru/mam_mol#432]
Подскажите, пожалуйста, как представить в Tree следующий json:
```json
{
  "a\nb\nc": {
    "\n": {
      "d": 7
    }
  }
}
```

Если имя узла в Tree не может содержать переводов строк, а многострочный текст должен быть искусственно представлен в виде списка узлов.

**Comment by nin-jin** [comment]
```tree
*
	\
		\a
		\b
		\c
		*
			\
				\
				\
				*
	  				d 7
```

**Comment by nin-jin** [comment]
Если будут ещё вопросы по этой теме, то можно воспользоваться [песочницей](https://tree.hyoo.ru/#source=%7B%0A%09%22primitives%22%3A%20%5B%0A%09%09%22https%3A%2F%2Fgithub.com%2Fnin-jin%2Ftree.d%2Fwiki%2Fjson.tree%22%2C%0A%09%09true%2C%0A%09%09777%2C%0A%09%09null%0A%09%5D%2C%0A%09%22foo%5Cnbar%22%3A%20%22xxx%5Cnyyy%22%0A%7D/pipeline=%24mol_json_from_string~%24mol_tree2_from_json).
