### ISSUE TITLE
Очень интересно, но ничего не понятно.

### ISSUE THREAD

**Issue by elite174** [hyoo-ru/mam_mol#440]
# Problem

Гуляя по просторам хабра, я наткнулся на вот эту статью.
https://habhub.hyoo.ru/#author=nin-jin/repo=HabHub/article=23

Я клюнул на описание mol не из-за того, что это очередной BRANDNEWFRAMEWORK (как оказалось, вовсе и не new), а из-за того, что в нём по заверению создателя решаются проблемы, с которыми я сталкивался при использовании других фреймворков/библиотек.

С горящими глазами я перешёл на страницу проекта, думая "ДАВАЙ ЕГО СЮДА! Я ХОЧУ ПРОБОВАТЬ!", но к своему разочарованию я не нашёл ни одной толковой инструкции и документации.
Да, есть набор методов с пояснениями (как их использовать? когда? зачем? что за синтаксис?).
Да, есть какие-то initial projects, которые надо скопировать, и магическим образом всё будет работать.
Но чёрт возьми, я хочу узнавать всё с нуля. Где понятная документация с примерами и шагами?
Я хочу понять, как мне писать простые приложения поэтапно.

# Solution

Пожалуйста, выкатите нормальный, ПОШАГОВЫЙ туториал, чтобы можно было с самого 0 реализовать простое приложение (а в дальнейшем добавлять усложнения). Технология выглядит очень интересной, но отсутствие внятных инструкций делает её изучение невозможным (иначе сейчас бы все писали на mol).

**Comment by nin-jin** [comment]
Тут есть несколько туториалов: https://github.com/hyoo-ru/mam_mol#quick-start
