### ISSUE TITLE
$mol_pick_time - user friendly time picker

### ISSUE THREAD

**Issue by nin-jin** [hyoo-ru/mam_mol#449]
![](https://habrastorage.org/webt/iv/s6/qg/ivs6qgpg9n74s1chnptnw7avf14.png)

**Comment by nin-jin** [comment]
![](https://i.imgur.com/tahmkPk.png)

**Comment by nin-jin** [comment]
Похожий компонент - $mol_date

**Comment by PavelZubkov** [comment]
А не рассматривал вариант позиционного ввода? При редактировании выводятся цифры-кнопки от 0 до 9 и стрелки лево/право, а на самом поле подсвечивается какая цифра сейчас редактируется.

Отличия от простого ввода с клавиатуры:
   - можно покликать мышкой не убирая руки на клавиатуру, или пальцем не выводят системную клавиатуру на пол экрана
   - нельзя ввести невалидное время, т.к. часть кнопок заблокирована
   
на два клика больше и менее привычно, но меньше кнопок

**Comment by nin-jin** [comment]
Лучше всё же дать обычное поле ввода, чтобы не переизобретать копипаст, дрегендроп и не ломать автозаполнение.
А вот ввод в режиме замены вместо вставки бы не помешал.

**Comment by stan-donarise** [comment]
Вроде транспонированные кнопки поприятнее?
![2023-03-08 19 27 53](https://user-images.githubusercontent.com/111230475/223662127-dc10369e-93f7-486e-ba89-b9a7746bbfba.png)

**Comment by nin-jin** [comment]
Да, думаю так будет проще искать, когда меньше переносов.
