### ISSUE TITLE
Not able to use spread when destructuring object

### ISSUE THREAD

**Issue by osv** [hyoo-ru/mam_mol#450]
# Describe the bug

Seems like bundler does not include some generated code, __rest function is missing for spreading

# To Reproduce

add in any place next code
```js
            const obj = { foo: 1, bar: 2 };
            const { foo, a ...restObjectItems } = obj;
```

# Actual

I can see next error
```
ReferenceError: __rest is not defined
```

generated code in web.js:

```js
                const obj = { foo: 1, bar: 2 };
                const { foo, a } = obj, restObjectItems = __rest(obj, ["foo", "a"]);
```

# Expected behavior

I can use spread when destructuring object

# Environment

Desktop:
 - OS: Ubuntu
 - Browser chromium
 - Version 90

# Additional context

Array destructuring with spread works fine:
```js
                const arr = [1, 2, 3];
                const [item1, ...restItems] = arr;
```

**Comment by nin-jin** [comment]
According to [es2018 support](https://caniuse.com/?feats=mdn-javascript_builtins_regexp_dotall,mdn-javascript_builtins_regexp_lookbehind_assertion,mdn-javascript_builtins_regexp_named_capture_groups,mdn-javascript_builtins_regexp_property_escapes,mdn-javascript_builtins_symbol_asynciterator,mdn-javascript_functions_method_definitions_async_generator_methods,mdn-javascript_grammar_template_literals_template_literal_revision,mdn-javascript_operators_destructuring_rest_in_objects,mdn-javascript_operators_spread_spread_in_destructuring,promise-finally) I have changed typescript target from ES2017 to ES2018. So __rest already doesn't required.

You may update MAM to get it:

```
git pull
```

**Comment by osv** [comment]
I see, changed target, works fine
```diff
-		"target": "ES2017",
+		"target": "ES2018",
```

Btw, I'm thinking, maybe there will be another helper generated by typescript but not included by bundler, so I'm thinking how it works... just concat ts compiled files?

**Comment by nin-jin** [comment]
Yes, compiler just concats the scripts. Global helpers are defined [there](https://github.com/hyoo-ru/mam/blob/master/mam.jam.js) and are included before all other code to the bundle.

**Comment by osv** [comment]
yeah, I checked jam file,but it is so small so I ignored it. Thanks
