### ISSUE TITLE
Cache-Control: no-cache для test.html

### ISSUE THREAD

**Issue by PavelZubkov** [hyoo-ru/mam_mol#460]
Где-то видел / слышал предложение отключать кеш для test.html страницы. Имеет смысл?

**Comment by nin-jin** [comment]
Тогда невозможно будет локально проверить работу с кешированием. Тут лучше будет просовывать в хтмл версию ресурсов. Например, из такого:

```html
<script src="web.js?{time}"></script>
```

Делать такое:

```html
<script src="web.js?2021-08-04T12:00:00.000+03:00"></script>
```

**Comment by nin-jin** [comment]
Прописал must-revalidate, чтобы не засирать кэш.

**Comment by PavelZubkov** [comment]
Это ишью можно закрыть значит?

**Comment by nin-jin** [comment]
Если нет нареканий, то конечно.
