### ISSUE TITLE
Ссылка сливается с общим фоном инструкции

### ISSUE THREAD

**Issue by Lyumih** [hyoo-ru/mam_mol#510]
Сайт: https://mol.hyoo.ru/  
Раздел: https://mol.hyoo.ru/#!Description=Create%20your%20application%20component

Ссылка "[declarative component description](https://github.com/hyoo-ru/mam_mol/tree/master/view)" сливается с общим выделением текста ( не выделена синим).
Фактический результат: ссылка розовая, не синяя
![image](https://user-images.githubusercontent.com/32732179/209070667-c97430c5-b6eb-4f93-af90-ab028088b611.png)

Ожидаемый результат: ссылка синия как все ссылки
![image](https://user-images.githubusercontent.com/32732179/209070923-69fc619a-d5f5-4ae3-b367-8c1f18060058.png)

**Comment by nin-jin** [comment]
Поправил, теперь так:
![image](https://user-images.githubusercontent.com/442988/209073424-3838890b-9955-433c-8515-d4b21ff01799.png)
