### ISSUE TITLE
Bug with button showcase

### ISSUE THREAD

**Issue by X7Becka** [hyoo-ru/mam_mol#524]
# Describe the bug
A chto za huinya s knopkami?

# To Reproduce
Beri huy v ruku i davay showcase po krugu

# Expected behavior
Doljno rabotat

# Screenshots
<img width="1690" alt="image" src="https://user-images.githubusercontent.com/51074290/211171288-7efc629e-3b90-4ee3-b5e0-57a700c2dec5.png">

# Environment
MacOS Chrome

# Additional context

**Comment by nin-jin** [comment]
Eti ibannie knopari viebivajutsa pokazivaja kak eti padli umejut tupit' i pred'javi pokazivat', tak chto otebis' ot nih.
