### ISSUE TITLE
Маркетинг слишком токсичный, идеи в фреймворке интересные.

### ISSUE THREAD

**Issue by emptyhere** [hyoo-ru/mam_mol#613]
# Topic

# Sommon

- @nin-jin - $mol maintainer.

**Comment by nin-jin** [comment]
Маркетинга у нас нет, а топик этот зачем?

**Comment by koplenov** [comment]
Хей, что если этот issue перерастёт в статью на какой-нибудь хабр? :D

Выше автор верно отметил, что маркетинга в настоящее время как такового нет

> Маркетинг слишком токсичный

Похоже речь о зубодробительных статьях Дмитрия, где в основном выделяется технический аспект без подбора слов

Если вам не по душе его тон и манера речи, почему бы не обратить внимание на усилия комьюнити?
Например, статьи:
* https://habr.com/ru/articles/662680/
* https://habr.com/ru/articles/732934/
* https://habr.com/ru/articles/741040/

Или посетить наш чатик и узнавать сообщество да сам фреймворк там:
* https://t.me/h_y_o_o
* https://t.me/mam_mol

Если вас не привлекает "токсичность"/троллинг автора, то всегда можно сплотиться в сообщество, верно? :D

Дмитрий выражал, что не старается продать кому-то фреймворк, он просто делает его для разработчиков

> идеи в фреймворке интересные

Огонь! Так почему бы не вложиться в дружелюбность к новичкам? :P

Дмитрий посвящает себя и своё время на разработку своего фреймворка, при этом также активно помогает другим в чатиках.
Делает сравнительные видео о других решениях https://www.youtube.com/@mam_mol/videos
Также активно ведёт новостную составляющую и не забывает подсвечивать вклад других https://t.me/mol_news

Так может мы, как сторонние наблюдали, чей свежий взор поможет снизить пороги для новичков и будем заниматься этим вашим маркетингом?

Маркетинга нет, но с начала года наше комьюнити стало больше на 50+ человек (темпы роста кратно выросли O_o), среди них также выявились активные персонажи

Я это к чему
К тому что давайте больше решать issue, нежели их создавать :D

https://mol.hyoo.ru/#!section=docs/=8x7cqq_d8e0xn
