### ISSUE TITLE
MAM ошибка разрешения зависимости, пути начинающиеся с папки с 1символом в имени

### ISSUE THREAD

**Issue by admenmod** [hyoo-ru/mam_mol#689]
# Как получить ошибку
1. Установить и проинициализировать репозиторий как описано в readme
2. Создать папку с 1 символом в качестве названия (/u/ | /o/)
3. Создать любой минимальный проект в этой папке (/u/main/)
4. Создать где то в этой же папке модуль - инструмент - view.tree (/u/main/dev/)
5. Использовать в u/main модуль u/main/dev
6. Запускаем проект u/main/ и видим ошибку что $u_main_dev незуществует

**Comment by nin-jin** [comment]
Это фича такая - в имении должно бить не менее 2 букв. Возможно стоит убрать это ограничение и просто не пропускать в глобальный реестр столь коротки имена.

**Comment by admenmod** [comment]
Я думаю достаточно было бы это четко обозначить, а то это выглядит так как будто оно просто ламается, я потратил 3дня прежде чем разобратся

**Comment by nin-jin** [comment]
Ослабил ограничение - теперь односимвольные неймспейсы тоже находятся.
